// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package raspberrypi.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class GPIO_Analog_Output extends CustomJavaAction<java.lang.Boolean>
{
	private raspberrypi.proxies.Raspberry_GPIO_Port PortNumber;
	private java.math.BigDecimal State;

	public GPIO_Analog_Output(IContext context, java.lang.String PortNumber, java.math.BigDecimal State)
	{
		super(context);
		this.PortNumber = PortNumber == null ? null : raspberrypi.proxies.Raspberry_GPIO_Port.valueOf(PortNumber);
		this.State = State;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GPIO_Analog_Output";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
