// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package raspberrypi.actions;

import raspberrypi.RaspberryPi;
import raspberrypi.proxies.Raspberry_Pin_Mode_Output;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.pi4j.io.gpio.GpioController;
import com.pi4j.io.gpio.GpioFactory;
import com.pi4j.io.gpio.Pin;

public class Provision_GPIO_Output extends CustomJavaAction<java.lang.Boolean>
{
	private raspberrypi.proxies.Raspberry_GPIO_Port PortNumber;
	private raspberrypi.proxies.Raspberry_Pin_Mode_Output PinMode;

	public Provision_GPIO_Output(IContext context, java.lang.String PortNumber, java.lang.String PinMode)
	{
		super(context);
		this.PortNumber = PortNumber == null ? null : raspberrypi.proxies.Raspberry_GPIO_Port.valueOf(PortNumber);
		this.PinMode = PinMode == null ? null : raspberrypi.proxies.Raspberry_Pin_Mode_Output.valueOf(PinMode);
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (this.PortNumber == null) {
			throw new IllegalArgumentException("Port Number is needed");
		}
		if (this.PinMode == null) {
			throw new IllegalArgumentException("Pin Mode is needed");
		}

		final GpioController gpio = GpioFactory.getInstance();
		final Pin pin = RaspberryPi.getRaspberryPiPin(this.PortNumber);
		
		if (this.PinMode == Raspberry_Pin_Mode_Output.Analog_Output) {
			gpio.provisionAnalogOutputPin(pin);
		} else if (this.PinMode == Raspberry_Pin_Mode_Output.Digital_Output) {
			gpio.provisionDigitalOutputPin(pin);
		} else if (this.PinMode == Raspberry_Pin_Mode_Output.Pwm_Output) {
			gpio.provisionPwmOutputPin(pin);
		} else if (this.PinMode == Raspberry_Pin_Mode_Output.Soft_Pwm_Output) {
			gpio.provisionSoftPwmOutputPin(pin);
		} else {
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Unknown Pin Mode");
		}
		
		gpio.shutdown();
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "Provision_GPIO_Output";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
