// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package raspberrypi.actions;

import java.math.BigDecimal;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import raspberrypi.TMP102;
import raspberrypi.RaspberryPi;

/**
 * Gets temperature in Celsius from a TMP102 sensor that has been hooked up to the SDA/SCL ports
 */
public class TMP102_GetTemperature extends CustomJavaAction<java.math.BigDecimal>
{
	public TMP102_GetTemperature(IContext context)
	{
		super(context);
	}

	@Override
	public java.math.BigDecimal executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		// We'll have to make this configurable. Right now it's fine
		final TMP102 tmp = new TMP102(0x48);
		final double temperature = tmp.getTemperature();
		tmp.close();
		
		return new BigDecimal(temperature);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "TMP102_GetTemperature";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
